spring.application.name=alumnos

spring.datasource.url=mysql://${{MYSQLUSER}}:${{MYSQL_ROOT_PASSWORD}}@${{RAILWAY_TCP_PROXY_DOMAIN}}:${{RAILWAY_TCP_PROXY_PORT}}/${{MYSQL_DATABASE}}
spring.datasource.username=raíz
spring.datasource.password=PTXOtKkvZcpNWIkohoGGFgWmQxBNDLDP
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081