spring.application.name=alumnos

spring.datasource.url=${jdbc:mysql://RAILWAY_PRIVATE_DOMAIN:3306/railway}
spring.datasource.username=${root}
spring.datasource.password=${PTXOtKkvZcpNWIkohoGGFgWmQxBNDLDP}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081